Basic logic for recording & simulation of events
Mihinator3000/AutoClicker pull request #2
Opened 2021-08-11 00:12 UTC by Mihinator3000

2021-08-13 20:23 UTC, Mihinator3000 commented
@hrrrrustic, можешь пожалуйста пр заревьюить, если не сложно?

2021-08-13 20:24 UTC, hrrrrustic commented
Да, сейчас 
Пингуй смелее (не знаю как остальных, меня точно можешь когда угодно)

2021-08-13 20:50 UTC, hrrrrustic reviewed
Верстку опять же не смотрел

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +namespace AutoClicker.Information
Не вижу ни одной причины, чтобы хранить столько типов в одном файле

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +        public void Execute();
В интерфейсах не надо указывать модификатор

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +            SimulateInput.MouseEvent(_mouseMessage);
Не совсем понимаю, почему у тебя `SimulateInput` сам по себе не статичный, но все методы статичны в итоге
Да и вообще не понял почему все в статике, это какое-то ограничение для вызова нативщины?

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +            var coordsContent = input.Split(", ");
тут же бай дизайн запятая с пробелом, да?

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +            MouseCursor.SetCursorPosition(_mousePoint);
Похоже на ситуацию с `SimulateInput`, но вот именно тут кмк можно просто сделать весь класс статичным
Здесь чем-то похожа ситуация на класс консоли, а `SimulateInput` - нет. Там просто у тебя какой-то класс для симуляции. (Переименуй его кстати в что-то вроде UserInputSimulator)
cc: @FrediKats

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +    public class Parser
Не особо информативное название)

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +        public static bool TryParse(string input, out List<IAction> actionList)
Не вижу ни одной причины, почему это должно быть статичным

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +        public static bool TryParse(string input, out List<IAction> actionList)
__
```suggestion
        public static bool TryParse(string input, out IReadOnlyList<IAction> actionList)
```

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/ViewModels/FullViewModel.cs
> +            if (!ActionInProgress)
Ты ведь понимаешь, что это не нормальная проверка на какую-то параллельность?
Я не особо знаю контекст этого кода и сходу не пойму
Но если ты пытаешься выполнять какие-то задачи последовательно (чтобы несколько одновременно не выполнялось, или только какое-то ограниченное количество), то это не вариант
Попробуй кратко объяснить, что это, для чего, чего пытаешься добиться

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/ViewModels/FullViewModel.cs
> +                if (!Parser.TryParse(TextBoxInput, out List<IAction> actionList))
Я ведь именно на это выше кидал предложение про ридонли, да?

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/ViewModels/FullViewModel.cs
> +            _lastActionTime = DateTime.Now;
Я думаю тебе это не критично, но мне кажется лучше засетить `DateTime.Now` в начале метода в переменную и потом ее использовать и в `timeBetweenActions`, и тут
Сам по себе вызов не дешевый, да и концептуально у тебя сейчас время как-то странно считается, время _окончания_ вызова последнего экшна и время _начала_ нового
Но это так, мелочь

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/ViewModels/ListenerViewModel.cs
> +            PickingInProgress = false;
Опять же мне кажется, что ты пытаешься как-то синхронизировать какие-то действия между собой, опиши опять что, как, зачем

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Ты же знаешь, что датаконтекст можно сетить внутри файла с версткой?
Или ты целенаправленно сетишь тут? Насколько я помню, оба варианты считаются нормальными, просто уточняю

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
А это зачем вообще?

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/InputSimulation/MouseActions.cs
> +            MouseMessages mouseUp)
Зачем тут перенос-то? 😄

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/InputSimulation/MouseCursor.cs
> +        [DllImport("user32.dll", EntryPoint = "SetCursorPos")]
Я же правильно понимаю, что ты бай дизайн поддерживаешь только винду? (я надеюсь ты понимаешь, что это ну вообще никак не заработает на линухе/маке)

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/InputSimulation/MouseCursor.cs
> +                currentMousePoint = new MousePoint(0, 0);
Я чет не обращал внимания, но если у тебя есть много мест, где нужно создавать вот такие (0,0), то мб есть смысл сделать что-то вроде `MousePoint.ZeroPoint`

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/InputSimulation/SimulateInput.cs
> +            input.U.mi.DwFlags = mouseMessage;
Господи выглядит ужасно x)
Вообще кажется на атрибутах можно разметить с какими названиями маршаллить, чтобы в коде это было человеко-читаемым, но пофиг, маршаллинг и так не человеко-читаем 😆

2021-08-13 20:50 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/Listener/GlobalHook.cs
> +    public class KeyPressedArgs : EventArgs
Ты экономишь файлы или что?)

2021-08-13 20:52 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
Это именно к 16 строке было

2021-08-13 21:12 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo.cs
> +            SimulateInput.MouseEvent(_mouseMessage);
SimulateInput поправил. А по поводу статики не особо понял, что не так?

2021-08-13 21:13 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo.cs
> +            var coordsContent = input.Split(", ");
Ага, потом поправлю, чтоб можно было и без пробела писать

2021-08-13 21:18 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo.cs
> +        public static bool TryParse(string input, out List<IAction> actionList)
Опять же не понимаю, что тут не так в статике, `TryParse` вроде все static. 
А в листе я делаю изменения, так что пока оставлю обычным листом

2021-08-13 21:21 UTC, Mihinator3000 commented on AutoClicker/ViewModels/FullViewModel.cs
> +            if (!ActionInProgress)
Ну в общем то да, это чтобы нельзя было одновременно запустить два и более выполнений. А как это по нормальному делать нужно?

2021-08-13 21:21 UTC, Mihinator3000 commented on AutoClicker/ViewModels/FullViewModel.cs
> +                if (!Parser.TryParse(TextBoxInput, out List<IAction> actionList))
+

2021-08-13 21:22 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +        public static bool TryParse(string input, out List<IAction> actionList)
Он статичен почти всегда, да, но он висит на конкретном типе, который ты парсишь
А тут у тебя этот метод внутри класса парсер, я вижу себе это так:
У тебя прокидывается парсер куда нужно, и от инстанса уже вызывается все что нужно

Про лист - ок

2021-08-13 21:23 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +            SimulateInput.MouseEvent(_mouseMessage);
Ну, я не понимаю, почему этот класс весь в статике, а не какой-нибудь InputSimulator, который прокидывается куда нужно

2021-08-13 21:32 UTC, Mihinator3000 commented on AutoClicker/ViewModels/ListenerViewModel.cs
> +            PickingInProgress = false;
Ну у меня есть действие `ActionInProgress`, отвечающее за выполнение действий симуляции в данный момент, есть `PickingInProgress`, отвечающий за установку координат, я старался сделать, чтобы они одновременно не могли быть оба `true`

2021-08-13 21:32 UTC, hrrrrustic commented on AutoClicker/ViewModels/FullViewModel.cs
> +            if (!ActionInProgress)
Ага, понял
Блин, синхронизация вопрос сложный
В целом проблема в том, что если у тебя параллельно что-то делается, то у тебя ноль гарантий, что после вот этого ифа с проверкой где-то в этот же момент не начнется что-то выполнять в другом потоке

Ну то есть грубо говоря ты ультрасупер быстро клацнул два раза на кнопку, которая это запускает
Получается, что у нас первая задача стартанула
А второй обработчик клика вполне мог пройти иф до старта первой задачи и начать выполнять свою
Итого у нас все равно две одновременно выполняется

Как делать нормально - есть примитивы синхронизации. Самый простой - lock, который скорее всего тебе тут и подойдет
Опять же, мне на глаз сложно понять архитектуру и иерархию классов, но вроде как, тебе просто нужно сделать в самом базовом классе какой-то object, на который ты будешь делать лок (предполагаю, что ты почитаешь про лок, чтобы понять мое предложение)

А вообще думаю, что @FrediKats, в силу специфики своей работы, может лучше подсказать, как начать что-то понимать в многопоточности

2021-08-13 21:37 UTC, Mihinator3000 commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Я тут его `set`ю, только для установки `CloseAction` и `EventHandler`ов `Loaded`, `Closing`. Не знаю насколько это правильно, если честно

2021-08-13 21:39 UTC, Mihinator3000 commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
Я не был особо уверен, что просто значение написать корректно будет

2021-08-13 21:40 UTC, Mihinator3000 commented on AutoClicker/WorkWithDll/InputSimulation/MouseCursor.cs
> +                currentMousePoint = new MousePoint(0, 0);
Логично, но это вроде единственное место

2021-08-13 21:42 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo.cs
> +            SimulateInput.MouseEvent(_mouseMessage);
Так по-моему намного удобнее просто

2021-08-13 21:45 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo.cs
> +        public static bool TryParse(string input, out List<IAction> actionList)
Опять таки, не очень понимаю зачем нам его прокидывать, когда можно просто вызвать напрямую

2021-08-13 21:47 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +            SimulateInput.MouseEvent(_mouseMessage);
Не ну понятно, что статику вызывать удобнее )
Это не считается за аргумент!

2021-08-13 21:47 UTC, Mihinator3000 commented on AutoClicker/ViewModels/FullViewModel.cs
> +            if (!ActionInProgress)
Хорошо, спасибо большое, посмотрю

2021-08-13 21:47 UTC, hrrrrustic commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Да это так, забей
Просто посмотри, что можно внутри xaml верстки тоже сетить контекст

2021-08-13 21:48 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
Я просто не совсем понял для чего этого
Это для маршаллинга надо или ты где-то у себя используешь?

2021-08-13 21:48 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/InputSimulation/MouseCursor.cs
> +                currentMousePoint = new MousePoint(0, 0);
А, ну тогда не надо

2021-08-13 21:54 UTC, Mihinator3000 commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Ну я его как раз и там, и там сетю, по этому в правильности не уверен

2021-08-13 21:55 UTC, hrrrrustic commented on AutoClicker/Information/FullInfo.cs
> +        public static bool TryParse(string input, out List<IAction> actionList)
Ну, конкретно тут - Parser.TryParse(...) выглядит супер странно (даже если переименовать класс в более информативный), для парсера я все-таки ожидаю new Parser(...).{Try}Parse
А в целом - ну статика это не круто. Удобно, быстро, стильно, молодежно - но не круто

Но вообще верю, что во всяких wpf может быть грустно все это прокидывать

@FrediKats Что скажешь? Кмк не особо критично. Я просто со слезами вспоминаю как я di контейнер заводил в впф

2021-08-13 21:55 UTC, Mihinator3000 commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
Да, для маршаллинга

2021-08-13 22:00 UTC, hrrrrustic commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
А
Ну если работает...
Но вообще в теории в этом конструкторе он уже должен быть не null, попробуй в дебаге поставить брейкпоинт и посмотреть
Мне кажется там уже должна быть твоя вьюмодель и тебе просто нужно датаконтекст кастануть к нужному типу

2021-08-13 22:00 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
А можно линк куда-нибудь, откуда ты там брал описание чего вообще надо

2021-08-13 22:20 UTC, Mihinator3000 commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Да, в конструкторе он уже стоит на моей вьюмодел. Про каст не очень понял опять таки, мне нужно просто для самой viewmodel свойство закрытия определить, без присваивания датаконтекст это не работает

2021-08-13 22:22 UTC, Mihinator3000 commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput

2021-08-13 22:30 UTC, hrrrrustic commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Ааа, все, понял
Ну тогда можно забить, будет слишком кринжово выглядеть

Я просто предлагал доставить из контекста твою модель тип
```C#
var vm = (чета-тамViewModel)DataContext
```
И дальше все также
Но как бы профита с этого около нуля

2021-08-13 22:31 UTC, hrrrrustic commented on AutoClicker/WorkWithDll/DataStructures.cs
> +        internal static int Size => Marshal.SizeOf(typeof(Input));
Хех, выглядит канеш стремно )0

2021-08-13 22:35 UTC, Mihinator3000 commented on AutoClicker/Views/FullWindow.xaml.cs
> +            DataContext = vm;
Получается ничего переделывать не надо :)

2021-08-15 22:53 UTC, FrediKats commented on AutoClicker/Information/FullInfo.cs
> +            SimulateInput.MouseEvent(_mouseMessage);
hrrrrustic хотел сказать, что статические методы лучше не использовать т.к., несмотря на простоту в их использовании, в дальнейшем очень сильно усложняется поддержка такого кода. Статика порождает сильную связанность между классами, ужасный уровень инкапсуляции и усложняет возможность применения ОО-кода.

2021-08-15 23:11 UTC, FrediKats requested changes
Немного докинул про декомпозицию и ОО-дизайн.

2021-08-15 23:11 UTC, FrediKats commented on AutoClicker/ViewModels/LiteViewModel.cs
>          public uint Duration { get; set; } = 1000;
У тебя в перемешку методы и поля. очень сложно читать класс этот.

2021-08-15 23:11 UTC, FrediKats commented on AutoClicker/ViewModels/LiteViewModel.cs
> +        public bool TryParse(out LiteClickerInfo task)
Я бы попробовал уменьшить сложность этого класса за счёт выделения этой логики, например. Сделать у LiteClickerInfo метод TryCreate, унести внутрь него MinClicksPerSecond и MaxClicksPerSecond.

2021-08-15 23:11 UTC, FrediKats commented on AutoClicker/ViewModels/LiteViewModel.cs
> +                MouseCursor.SetCursorPosition(startPos);
Вот эта логика тоже не кажется, что должна быть частью VM. Это какая-то логика выполнения. Я бы выделил её в отдельную сущность, а во VM только создавал её и тыкал в ней метод Execute. И да, методы обычно называют глаголами - Execute вместо Execution.

2021-08-15 23:11 UTC, FrediKats commented on AutoClicker/Information/LiteInfo.cs
> +        public LiteClickerInfo(
Какой-то странный получается класс, который хранит в себе _очень_ много информации, но при этом ничего не умеет делать (0 методов у него). Возможно, он где-то должен инкапсулировать в себе логику. Возможно, проблема в том, что он назван странно и нет понимания за что он отвечает. Подумай над названием и тем, что он делать должен. Возможно, методы в нём после этого появятся.

2021-08-15 23:11 UTC, FrediKats commented on AutoClicker/Information/FullInfo/Actions/KeyAction.cs
> +        public bool TryParse(string input)
Мне очень не нравится то, что объект сначала создаётся не инициализированным, а потом вызовом метода TryParse инициализируется.

2021-08-16 06:57 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo/Actions/KeyAction.cs
> +        public bool TryParse(string input)
Может тогда лучше просто переименовать его в TryCreate?

2021-08-16 21:30 UTC, FrediKats commented on AutoClicker/Information/FullInfo/Actions/KeyAction.cs
> +        public bool TryParse(string input)
Тогда странно, что этот метод ничего не создаёт и будет называться Create)

2021-08-16 23:26 UTC, Mihinator3000 commented on AutoClicker/Information/FullInfo/Actions/KeyAction.cs
> +        public bool TryParse(string input)
TryInitialize?

2021-08-17 00:26 UTC, Mihinator3000 commented on AutoClicker/ViewModels/FullViewModel.cs
> +            if (!ActionInProgress)
@hrrrrustic, я тут почитал про lock и примитивы синхронизации, попробовал у себя их реализовать. Правда как я понял, работает это по принципу: если поток не заходит в lock, он ждет пока занимающий его поток не освобождается, и после этого сам заходит в lock. 
Мне то просто нужно, чтобы поток не ожидал выполнение предыдущего, а пропускал lock, то есть вызовы не стакались друг на друге. 
Можешь пожалуйста сказать, это также реализуется через те самые примитивы синхронизации и мне просто стоит еще пару дней с этим посидеть? (Надеюсь я щас не полный бред написал :))

2022-09-23 00:29 UTC, merged

2022-09-23 00:35 UTC, hrrrrustic commented
Господи год уже прошел...

2022-09-23 01:37 UTC, Mihinator3000 commented
Надо же было когда-то пр закрыть..